export * as userApi from './user'
export * as addressApi from './address'
export * as categoryApi from './category'
export * as goodsApi from './goods'
export * as seckillApi from './seckill'
export * as orderApi from './order'
export * as payApi from './pay'
export * as adminApi from './admin'
export { request } from './request'
export * from './types'
